### ISSUE TITLE
Duplicate ORF ID entries in orf table

### ISSUE THREAD

**Issue by JackDettoLoco** [jtamames/SqueezeMeta#969]
Hi,

I noticed that the  output table 13.project.orftable may contain duplicate entries for the same ORF ID.

For example, the following ORF appears twice in the table:

sep_MIBIREM_MG_MT_12494_1-138

This causes issues downstream when parsing the table or attempting to join it with other datasets based on ORF ID.

To temporarily solve the issue, I filtered the table using:

awk` '!seen[$1]++' file.tsv > `file_filtered.tsv

[wetransfer_original_file](https://we.tl/t-o9zio2Mf26)

Thanks!

**Comment by fpusan** [comment]
This should have fixed by 51f7147
Is this happening with version 1.7.0 or an older one?

**Comment by JackDettoLoco** [comment]
(SqueezeMeta) giacomo@grog:~$ SqueezeMeta.pl -v
1.7.0, Mar 2025

**Comment by fpusan** [comment]
Ok, I can see it. As far as I can tell it only happens for one ORF (sep_MIBIREM_MG_MT_12494_1-138).

For future reference, here's the context in the file:

############################################################################################
**sep_MIBIREM_MG_MT_12494_1-138**   sep_MIBIREM_MG_MT_12494 CDS     Prodigal        138     46      52.90           k_Eukaryota;n_Opisthokonta;n_Fungi;n_Dikarya;p_Ascomycota;n_saccharomyceta;n_Pezizomycotina;n_leotiomyceta;n_sordariomyceta;c_Sordariomycetes;n_Hypocreomycetidae;o_Hypocreales;f_Nectriaceae;g_Fusarium                          ENOG410Y9MV*            Function unknown                0   00       0       0.000   0.000   0.000   0.000   0.000   0.000   0.000   0.000   0       0       0       0       0.000   0.000   0.0000.000   0.000   0.000   0.000   0.000   0       0       0       0       0       0       0       0       0       0       0       0   00       0       0       0       0       0       0       0       0       0       0       25
sep_MIBIREM_MG_MT_124941_1-381  sep_MIBIREM_MG_MT_124941        CDS     Prodigal        381     127     62.73   cynT, can       k_Bacteria;p_Pseudomonadota;c_Alphaproteobacteria;o_Hyphomicrobiales;f_Hyphomicrobiaceae     K01673* carbonic anhydrase [EC:4.2.1.1] Metabolism; Energy metabolism; Nitrogen metabolism   COG0288*        Carbonic anhydrase      Inorganic ion transport and metabolism  PF00484 [Carbonic anhydrase] 0.649   0.000   0.229   0.226   0.000   0.047   0.000   0.000   0.003   0.000   0.000   0.000   63.462  0.0001.575   0.588   0.000   1.092   0.000   0.000   0.181   0.000   0.000   0.000   205     0       4       4       0       3       0   01       0       0       0       24179   0       600     224     0       416     0       0       69      0       0       0       25
**sep_MIBIREM_MG_MT_12494_1-138**   sep_MIBIREM_MG_MT_12494 CDS     Prodigal        138     46      52.90           k_Eukaryota;n_Opisthokonta;n_Fungi;n_Dikarya;p_Ascomycota;n_saccharomyceta;n_Pezizomycotina;n_leotiomyceta;n_sordariomyceta;c_Sordariomycetes;n_Hypocreomycetidae;o_Hypocreales;f_Nectriaceae;g_Fusarium                          ENOG410Y9MV*            Function unknown                0.0790.161   0.317   0.311   0       0       0       0       0       0       0       0       5.333   0.457   1.181   1.471   0       0   00       0       0       0       0       9       1       2       2       0       0       0       0       0       0       0       0   736      63      163     203     0       0       0       0       0       0       0       0       25
sep_MIBIREM_MG_MT_12494_1341-2945       sep_MIBIREM_MG_MT_12494 CDS     Prodigal        1605    535     54.95   dmpA, dap       k_Eukaryota;n_Opisthokonta;n_Fungi;n_Dikarya;p_Ascomycota;n_saccharomyceta;n_Pezizomycotina;n_leotiomyceta;n_sordariomyceta;c_Sordariomycetes;n_Hypocreomycetidae;o_Hypocreales;f_Nectriaceae;g_Fusarium  K01266* D-aminopeptidase [EC:3.4.11.19] Brite Hierarchies; Protein families: metabolism; Peptidases  COG1680*        Beta-lactamase class C and other penicillin binding proteins            PF00144 [Beta-lactamase];PF07930 [D-aminopeptidase, domain B]        0.067   0.637   0.789   0.509   0.000   0.000   0.000   0.000   0.000   0.0000.000   0.000   7.364   4.204   5.206   3.120   0.000   0.000   0.000   0.000   0.000   0.000   0.000   0.000   89      46      58  38       0       0       0       0       0       0       0       0       11819   6747    8355    5008    0       0       0       0   00       0       0       25
############################################################################################

So it appears twice, with one ORF in between both appearances. The first appearance has no abundance assigned to it.
I'll give it a thought and get back to you.

**Comment by fpusan** [comment]
Did the run get interrupted midway step 13 and restarted later?

**Comment by JackDettoLoco** [comment]
[link](https://we.tl/t-OKO0DF56Cb)

**Comment by fpusan** [comment]
Sorry, the link expired during Eastern break. Could you re-send?

**Comment by JackDettoLoco** [comment]
[same updated link](https://we.tl/t-nHgZjf8Mdj)

**Comment by fpusan** [comment]
Ok, so this happened because ORFs weren't completely ordered in the `10.*.mapcount` file.
The rows for `sep_MIBIREM_MG_MT_12494_1-138` (one row per sample) weren't together, but interrupted by `sep_MIBIREM_MG_MT_124941_1-381`. So, the way script 13 works, `sep_MIBIREM_MG_MT_12494_1-138` got written twice.

Funny enough, the way of sorting the file was changed in 98d7b5b so this issue may already be fixed in our dev version.

Could you install `squeezemeta-dev=1.7.1.alpha3` and re-run scripts 10 to 13?
- `10.mapsamples.pl /path/to/your/project`
- `11.mcount.pl /path/to/your/project`
- `12.funcover.pl /path/to/your/project`
- `13.mergeannot2.pl /path/to/your/project`

This should give you an ORF table with no duplicates.

**Comment by JackDettoLoco** [comment]
Hi, I'm out of office until Monday

Inviato da Outlook per Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by JackDettoLoco** [comment]
Hi,
I created a new conda environment using the following command:

`CONDA_OVERRIDE_CUDA=12.4 conda create -n SqueezeMeta_dev -c conda-forge -c bioconda -c fpusan squeezemeta-dev=1.7.1.alpha3 --no-channel-priority`
Then I ran:

`SqueezeMeta.pl --restart -p sep_MIBIREM_MG_MT -step 10 --force_overwrite`

After processing, I imported everything into R, but the issue persists:

`non-unique value when setting 'row.names': ‘sep_MIBIREM_MG_MT_12494_1-138’`

Would it be helpful if I provided the files generated in this latest run, or would you prefer files from earlier stages of the pipeline for further analysis?

Thank you for your assistance!

**Comment by fpusan** [comment]
Is there any chance that you could share the whole project directory? How large is it?
Otherwise at least can you at least share `/path/to/project/intermediate/10.*.mapcount`?

**Comment by JackDettoLoco** [comment]
the folder is 140 Gb. I share the file 
[10.sep_MIBIREM_MG_MT.mapcount](https://unipiit-my.sharepoint.com/:u:/g/personal/a050827_unipi_it/EZRCfd6Wa85DsqYxFlB261ABAixPprXjxTjsFw74D7IpCA?e=oBUGCC)

If you need the entire folder, I'll need some time to migrate all the files to OneDrive.

**Comment by fpusan** [comment]
Yeah the file still has the issue, I would need the entire folder then...

**Comment by fpusan** [comment]
Well, this is dumb.
Turns out that, the way SqueezeMeta is coded, it will use the old scripts when you restart an old project, even if you are using a new version. I have to look into that.
You can edit the `$installpath` variable inside the `/path/to/project/SqueezeMeta_conf.pl` file (not the one in the SqueezeMeta install dir) so it points to your new installation directory.

But anyways the good news is that the bug had indeed already removed in the development version. I've shared with you the corrected version of the mapcount file using OneDrive, from then you can restart from step 11 and you should get the right results.
